[package]
name = "trezor_lib"
version = "0.1.0"
authors = ["SatoshiLabs <info@satoshilabs.com>"]
edition = "2021"
build = "build.rs"

[features]
default = ["model_tt"]
bitcoin_only = []
model_tt = ["touch"]
model_t1 = ["buttons"]
model_tr = ["buttons"]
micropython = []
protobuf = ["micropython"]
ui = []
ui_debug = []
buttons = []
touch = []
clippy = []
test = ["cc", "glob", "micropython", "protobuf", "ui", "ui_debug"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
opt-level = 2
split-debuginfo = "unpacked"
codegen-units = 1
debug = 2

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
debug = 2

[profile.test]
split-debuginfo = "unpacked"

# Runtime dependencies

[dependencies.cty]
version = "0.2.2"

[dependencies.heapless]
version = "0.7.3"
default_features = false

[dependencies.cstr_core]
version = "0.2.4"
default_features = false

[dependencies.getrandom]
version = "0.2.6"
default_features = false
features = [ "custom" ]

[dependencies.trezor-crypto-lib]
git = "https://github.com/mobilecoinofficial/rust-trezor-crypto"
#optional = true
default_features = false

# Build dependencies

[build-dependencies.bindgen]
version = "0.60.1"
default_features = false
features = ["runtime"]

# Build dependencies used for linking the test binary

[build-dependencies.cc]
optional = true
version = "1.0.69"

[build-dependencies.glob]
optional = true
version = "0.3.0"

[patch.crates-io]
curve25519-dalek = { git = "https://github.com/ryankurte/curve25519-dalek", branch="feature/ffi-raw-conversions" }
ed25519-dalek = { git = "https://github.com/ryankurte/ed25519-dalek", branch="feature/generic-digests" }

[patch."https://github.com/mobilecoinofficial/rust-trezor-crypto"]
trezor-crypto-lib = { path = "../../../../mobilecoin/rust-trezor-crypto" }
